### ISSUE TITLE
Error when pushing commit

### ISSUE THREAD

**Issue by Barbaross93** [simeg/eureka#81]
Hi

Thanks for sharing this program! I can see it being very useful in my workflow. Unfortunately I seem to be encountering a problem. Trying the latest release and git versions, I get this error message:
```
Adding and committing your new idea..
Added and committed!
Pushing your new idea..
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/barbarossa/.cargo/registry/src/github.com-1ecc6299db9ec823/eureka-1.8.1/src/git.rs:88:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Box<Any>', /home/barbarossa/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.17/src/panic.rs:27:9
```
With RUST_BACKTRACE=1 I get:
```
Adding and committing your new idea..
Added and committed!
Pushing your new idea..
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/barbarossa/.cargo/registry/src/github.com-1ecc6299db9ec823/eureka-1.8.1/src/git.rs:88:47
stack backtrace:
   0: rust_begin_unwind
             at /build/rust/src/rustc-1.49.0-src/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /build/rust/src/rustc-1.49.0-src/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /build/rust/src/rustc-1.49.0-src/library/core/src/panicking.rs:50:5
   3: eureka::git::Git::get_callbacks::{{closure}}
   4: git2::remote_callbacks::credentials_cb::{{closure}}
   5: git2::panic::wrap
   6: git2::remote_callbacks::credentials_cb
   7: handle_auth
   8: handle_response.constprop.0
   9: http_stream_read
  10: git_smart__recv_cb
  11: git_smart__store_refs
  12: git_smart__connect
  13: git_remote_connect
  14: git2::remote::Remote::connect_auth
  15: eureka::git::Git::push
  16: eureka::Eureka<FH,W,R>::run
  17: eureka::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'Box<Any>', /home/barbarossa/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.17/src/panic.rs:27:9
stack backtrace:
   0: std::panicking::begin_panic
   1: git2::remote::Remote::connect_auth
   2: eureka::git::Git::push
   3: eureka::Eureka<FH,W,R>::run
   4: eureka::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
The repo is private, and I believe I have my credentials stored; so in theory, eureka should be pushing commits no problem. I think I might be missing something anyway, do you have any ideas?

**Comment by Javier-varez** [comment]
I also came across this issue. Make sure your remote is using ssh and has a username in the url. It probably should be fixed by using the USER environment variable if the username is not part of the url, but that may work for now as a workaround.

Also, sorry for the referenced commit above, it actually refers to a different issue.

**Comment by simeg** [comment]
Hi @Barbarossa93! Thanks for reporting.

I'm unable to reproduce this, but I've made a potential fix. If you could try it out locally that would be amazing (by cloning this repo, checking out the `fix-git-auth` branch and running `make build link && ./eureka`), if not I can release a new version and you can try it that way.

https://github.com/simeg/eureka/pull/83

**Comment by DanielRivasMD** [comment]
So I had the same problem as above. I followed your suggestion of clone and using `fix-git-auth`. It did not work. I get this other error message:

```
Adding and committing your new idea to master..
thread 'main' panicked at 'failed to write reference 'refs/heads/master': a reference with that name already exists.; class=Reference (4); code=Exists (-4)', src/bin/eureka.rs:82:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by LironHazan** [comment]
@simeg same happened to me using the **fix-git-auth** branch,

I tried to fix by deleting the first github repo I created (its default branch was "main" not "master" so I suspected that),
Afterwards I created a new github repo with "master" as its default branch, and removed the ' ~/.eureka/' path for a clean start, added the setup path of the new repo (default branch is master) and still got the same issue of:

"'refs/heads/master': a reference with that name already exists."

It seemed to me like a general git issue I could resolve manually so I went to the branch and have to add the commit,
I added it and pushed in order to be alined with master but that didn't resolve,  

```
➜  eureka-private git:(master) g status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   README.md

no changes added to commit (use "git add" and/or "git commit -a")
```

Original Issue: 

```
Adding and committing your new idea to master..
thread 'main' panicked at 'failed to write reference 'refs/heads/master': a reference with that name already exists.; class=Reference (4); code=Exists (-4)', src/bin/eureka.rs:82:19
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
   2: eureka::main
   3: core::ops::function::FnOnce::call_once

```

I'll ping here if I'll mange to resolve it..

**Comment by LironHazan** [comment]
I debugged a bit, removing the **map_err** from 'git_add_commit_push' will reveal the actual issue which is:

`'main' panicked at 'called `Option::unwrap()` on a `None` value', src/git.rs:109:26`

username = None

```
        callbacks.credentials(|_url, username, _allowed_types| {
            Cred::ssh_key(
                username.unwrap(),
                None,
                std::path::Path::new(&format!("{}/.ssh/id_rsa", env::var("HOME").unwrap())),
                None,
            )
        });
```

So I added my username hardcoded just for the check and and passed:

```
>> Idea summary
> efgefg
Adding and committing your new idea to master..
branch_name, master
Added and committed!
Pushing your new idea..
Pushed!
```

But nothing was actually pushed to the repo + when I do git status I saw that nothing was done,

```
➜  eureka-private git:(master) ✗ g status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   README.md

no changes added to commit (use "git add" and/or "git commit -a")
```
Umm so I'm not sure at all why add() doesn't actually work in that case, the weird thing is that everything seem to run without any errors :/

**Comment by felixg3** [comment]
I am experiencing a similar issue. 
How can I help to fix this?

```
Adding and committing your new idea..
Added and committed!
Pushing your new idea..
thread 'main' panicked at 'Something went wrong pushing: Error { code: -1, klass: 23, message: "Failed to retrieve list of SSH authentication methods: Failed getting response" }', /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/eureka-1.8.1/src/lib.rs:138:14
stack backtrace:
   0:     0x557146714990 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8cec7d3cc976ce29
   1:     0x557146730bcf - core::fmt::write::h857611cedfb31b47
   2:     0x5571467122a5 - std::io::Write::write_fmt::h8f0169f65119855e
   3:     0x557146716985 - std::panicking::default_hook::{{closure}}::h00d9c78adc95692f
   4:     0x557146716433 - std::panicking::default_hook::h9859b2464b63b070
   5:     0x557146716f9d - std::panicking::rust_panic_with_hook::hfa427c9780525830
   6:     0x557146716b27 - std::panicking::begin_panic_handler::{{closure}}::ha261ff243dc39b06
   7:     0x557146714e2c - std::sys_common::backtrace::__rust_end_short_backtrace::h2f5cc2d3be17fe34
   8:     0x557146716a89 - rust_begin_unwind
   9:     0x55714668dd41 - core::panicking::panic_fmt::h97e73db3d569daef
  10:     0x55714668dc33 - core::result::unwrap_failed::h98c4762a36f2ad2b
  11:     0x557146693338 - eureka::Eureka<FH,W,R>::run::heff5a0aeea537367
  12:     0x557146696132 - eureka::main::h22686d5b21fa27f2
  13:     0x5571466910d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h421da6dc99dbea44
  14:     0x5571466901c9 - std::rt::lang_start::{{closure}}::h542cf84e6a1f679d
  15:     0x55714671749a - std::rt::lang_start_internal::haf91469a0ba5ac00
  16:     0x5571466962d2 - main
  17:     0x7fbecc259b25 - __libc_start_main
  18:     0x55714668e3ce - <unknown>
                               at /home/abuild/rpmbuild/BUILD/glibc-2.33/csu/../sysdeps/x86_64/start.S:120
  19:                0x0 - <unknown>

```

**Comment by simeg** [comment]
Hi everyone!

I'm trying to understand the root problem. Seems like there might be more than one. I'm still unable to reproduce the problem so I suspect it's git using SSH vs. HTTPS. I use SSH but eureka should of course support both. I find the git2 library I'm using pretty confusing to work with, and there's no official examples for pushing unfortunately.

Here's another branch to try out (`fix-git-auth-2`). You can try it by cloning this repo, checking out the branch and running `make build link && ./eureka`. It will try to use SSH and if that fails it will use HTTPS. Please let me know how it works.

Just started my vacation so I won't be as slow to respond as before 🙂 

https://github.com/simeg/eureka/pull/84

**Comment by LironHazan** [comment]
@simeg No luck for me :/


```
Adding and committing your new idea to test..
Added and committed!
Pushing your new idea..
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', **src/git.rs:132:47**
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Box<Any>', /Users/lironh/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.17/src/**panic.rs:27:9**
```

Cred::ssh_key_from_agent(username.unwrap())
username seem to be NONE which panics git2

Enjoy your vacation :)

**Comment by simeg** [comment]
Hi @LironHazan!

Appreciate the quick response. I updated the branch again, please try again when you have the chance.

Vacation is awesome :D

**Comment by LironHazan** [comment]
@simeg Sure :)
I updated the branch and now I'm facing another issue,
Panics at src/bin/eureka.rs:82:19 

```
>> Idea summary
> fofofof
Adding and committing your new idea to test..
Added and committed!
Pushing your new idea..
thread 'main' panicked at 'remote authentication required but no callback set; class=Http (34)', src/bin/eureka.rs:82:19
```

**Comment by simeg** [comment]
@LironHazan Interesting! I'm unable to reproduce that as well.

1. Silly question maybe but are you able to push to other repos?
2. Do you have a private key file on your machine? `test -e $HOME/.ssh/id_rsa && echo "it exists"`
3. Do you have any special git configuration in `$HOME/.gitconfig`?

I pushed another commit with verbose debug logs. Please run it with thes `RUST_LOG` flag
```
make build link && RUST_BACKTRACE=full RUST_LOG=debug ./eureka
```

**Comment by LironHazan** [comment]
So firstly thanks a lot for helping! :)
1. Do you mean generally if I can push? so yes 🙌  I'm a pusher lol
2. Yes I have (exists!)
3. Looks pretty basic:

```
[core]
        autocrlf = input
[protocol]
        version = 2

```

4. trace 🚜 

```
/Users/lironh/.cargo/bin/cargo build
   Compiling eureka v1.8.1 (/Users/lironh/dev-liron/eureka)
    Finished dev [unoptimized + debuginfo] target(s) in 5.07s
 DEBUG eureka > Running with options: EurekaOptions { clear_repo: false, clear_branch: false, view: false }
>> Idea summary
> gg
Adding and committing your new idea to test..
Added and committed!
Pushing your new idea..
 DEBUG eureka > Pushing using SSH agent auth..
 DEBUG eureka::git > get_ssh_callbacks: got username: git
 DEBUG eureka::git > get_ssh_callbacks: allowed types is empty: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is default: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is ssh custom: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is ssh interactive: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is ssh key: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is ssh memory: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is username: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is user pass plaintext: true
 DEBUG eureka::git > get_ssh_callbacks: allowed types is all: false
 DEBUG eureka::git > get_ssh_callbacks: allowed_types does not contain username, resolving ssh key from agent
 DEBUG eureka::git > push: could not push due to error: remote authentication required but no callback set; class=Http (34)
 DEBUG eureka      > Failed to push using SSH agent auth, will try auth via SSH file..
 DEBUG eureka::git > get_https_callbacks: got username: git
 DEBUG eureka::git > get_https_callbacks: private key path: /Users/lironh/.ssh/id_rsa
 DEBUG eureka::git > push: could not push due to error: remote authentication required but no callback set; class=Http (34)
thread 'main' panicked at 'remote authentication required but no callback set; class=Http (34)', src/bin/eureka.rs:82:19
stack backtrace:
   0:        0x1037db4e4 - std::backtrace_rs::backtrace::libunwind::trace::h0e344f93e1be12b3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x1037db4e4 - std::backtrace_rs::backtrace::trace_unsynchronized::h547096f273f197d3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1037db4e4 - std::sys_common::backtrace::_print_fmt::h46deca35c22bc084
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x1037db4e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h80b40bec9b25cdb7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x1037f3c0e - core::fmt::write::h367e10cc391177e1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:        0x1037d8c36 - std::io::Write::write_fmt::h69f760cf0ceceb64
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:        0x1037dd2f9 - std::sys_common::backtrace::_print::h06c56467d8f0565c
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x1037dd2f9 - std::sys_common::backtrace::print::h83e6ec856bd254a6
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x1037dd2f9 - std::panicking::default_hook::{{closure}}::h6b461dbc832ae479
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:        0x1037dcde0 - std::panicking::default_hook::hf6b37b6d4ff1b717
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:        0x1037dd965 - std::panicking::rust_panic_with_hook::hcc0074a2cdf70335
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:        0x1037dd4a5 - std::panicking::begin_panic_handler::{{closure}}::hafebb92bbb4f046c
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  12:        0x1037db948 - std::sys_common::backtrace::__rust_end_short_backtrace::hbd3b6a5769847c0d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x1037dd40a - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:        0x1037fd22b - std::panicking::begin_panic_fmt::h7722ff9c8a9c34c7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
  15:        0x1033a5213 - eureka::main::h9130df9b52d9e903
  16:        0x1033a0a7e - core::ops::function::FnOnce::call_once::h9a6658880b37b5fa
  17:        0x1033a0e71 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha5f37245e5587bd6
  18:        0x1033a55a4 - std::rt::lang_start::{{closure}}::ha09c09781317f382
  19:        0x1037ddcd4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b22ce68aa2879c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  20:        0x1037ddcd4 - std::panicking::try::do_call::h51a4853c94b1bdea
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  21:        0x1037ddcd4 - std::panicking::try::ha45bc5eab1f103eb
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  22:        0x1037ddcd4 - std::panic::catch_unwind::h191bc002afc126a7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  23:        0x1037ddcd4 - std::rt::lang_start_internal::h0c37a46739a0311d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  24:        0x1033a557e - std::rt::lang_start::h4122b0820f04a803
  25:        0x1033a54c6 - _main
C
```

**Comment by simeg** [comment]
@LironHazan 

1. Looks like you're using macOS?
2. It looks like you haven't registered your SSH key with the ssh-agent. If you'd like, you can try [these instructions](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent). I'm pretty sure it will solve this issue.
3. Out of curiosity, did you setup a password for your SSH key? You can check using the "Keychain Access" app and searching for SSH -> open the key item -> Show password

Again, I appreciate your patience and quick responses 🙂

**Comment by LironHazan** [comment]
@simeg 😄 
1. Yes I'm using macOS
2. Cool I followed the instructions and registered my sshkey with the agent - the output looked good
`Identity added: /Users/lironh/.ssh/id_whatever (mymail@foo.com)`
The key itself was already added to the account a while ago so I skipped the last step of adding it,
But I still get the same error :/ (tried with a new session) 
3.  Do you mean the passphrase? I feel uncomfortable answering this question :)

Anyway, thanks for the help!

**Comment by simeg** [comment]
@LironHazan Thanks! Can you paste the output now that you added it to the agent?

3. Ok no worries 🙂

**Comment by LironHazan** [comment]
@simeg 
sure, it seems like the username wasn't grabbed by the agent or something :) 

```
>> Idea summary
> ddd
Adding and committing your new idea to test..
Added and committed!
Pushing your new idea..
 DEBUG eureka > Pushing using SSH agent auth..
 DEBUG eureka::git > get_ssh_callbacks: got username: git
 DEBUG eureka::git > get_ssh_callbacks: allowed types is empty: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is default: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is ssh custom: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is ssh interactive: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is ssh key: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is ssh memory: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is username: false
 DEBUG eureka::git > get_ssh_callbacks: allowed types is user pass plaintext: true
 DEBUG eureka::git > get_ssh_callbacks: allowed types is all: false
 DEBUG eureka::git > get_ssh_callbacks: allowed_types does not contain username, resolving ssh key from agent
 DEBUG eureka::git > push: could not push due to error: remote authentication required but no callback set; class=Http (34)
 DEBUG eureka      > Failed to push using SSH agent auth, will try auth via SSH file..
 DEBUG eureka::git > get_https_callbacks: got username: git
 DEBUG eureka::git > get_https_callbacks: private key path: /Users/lironh/.ssh/id_rsa
 DEBUG eureka::git > push: could not push due to error: remote authentication required but no callback set; class=Http (34)
thread 'main' panicked at 'remote authentication required but no callback set; class=Http (34)', src/bin/eureka.rs:82:19
stack backtrace:
   0:        0x10c66b4e4 - std::backtrace_rs::backtrace::libunwind::trace::h0e344f93e1be12b3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x10c66b4e4 - std::backtrace_rs::backtrace::trace_unsynchronized::h547096f273f197d3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10c66b4e4 - std::sys_common::backtrace::_print_fmt::h46deca35c22bc084
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10c66b4e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h80b40bec9b25cdb7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10c683c0e - core::fmt::write::h367e10cc391177e1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:        0x10c668c36 - std::io::Write::write_fmt::h69f760cf0ceceb64
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:        0x10c66d2f9 - std::sys_common::backtrace::_print::h06c56467d8f0565c
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10c66d2f9 - std::sys_common::backtrace::print::h83e6ec856bd254a6
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10c66d2f9 - std::panicking::default_hook::{{closure}}::h6b461dbc832ae479
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:        0x10c66cde0 - std::panicking::default_hook::hf6b37b6d4ff1b717
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:        0x10c66d965 - std::panicking::rust_panic_with_hook::hcc0074a2cdf70335
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:        0x10c66d4a5 - std::panicking::begin_panic_handler::{{closure}}::hafebb92bbb4f046c
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  12:        0x10c66b948 - std::sys_common::backtrace::__rust_end_short_backtrace::hbd3b6a5769847c0d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x10c66d40a - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:        0x10c68d22b - std::panicking::begin_panic_fmt::h7722ff9c8a9c34c7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
  15:        0x10c235213 - eureka::main::h9130df9b52d9e903
  16:        0x10c230a7e - core::ops::function::FnOnce::call_once::h9a6658880b37b5fa
  17:        0x10c230e71 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha5f37245e5587bd6
  18:        0x10c2355a4 - std::rt::lang_start::{{closure}}::ha09c09781317f382
  19:        0x10c66dcd4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b22ce68aa2879c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  20:        0x10c66dcd4 - std::panicking::try::do_call::h51a4853c94b1bdea
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  21:        0x10c66dcd4 - std::panicking::try::ha45bc5eab1f103eb
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  22:        0x10c66dcd4 - std::panic::catch_unwind::h191bc002afc126a7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  23:        0x10c66dcd4 - std::rt::lang_start_internal::h0c37a46739a0311d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  24:        0x10c23557e - std::rt::lang_start::h4122b0820f04a803
  25:        0x10c2354c6 - _main
```

**Comment by simeg** [comment]
@LironHazan Changed some more code, please try again on the same branch 😄

**Comment by LironHazan** [comment]
@simeg thanks for the commitment,
seems like something on my local config isn't playing well 
```
>> Idea summary
> gg
Adding and committing your new idea to test..
Added and committed!
Pushing your new idea..
 DEBUG eureka::git > get_callbacks: got username: git
 DEBUG eureka::git > get_callbacks: allowed types: USER_PASS_PLAINTEXT
 DEBUG eureka::git > get_callbacks: using credential helper
 DEBUG eureka::git > get_callbacks: got auth error: failed to acquire username/password from local configuration
 DEBUG eureka::git > push: could not push due to error: failed to acquire username/password from local configuration
thread 'main' panicked at 'failed to acquire username/password from local configuration', src/bin/eureka.rs:82:19
stack backtrace:
   0:        0x1046e6b34 - std::backtrace_rs::backtrace::libunwind::trace::h0e344f93e1be12b3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x1046e6b34 - std::backtrace_rs::backtrace::trace_unsynchronized::h547096f273f197d3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1046e6b34 - std::sys_common::backtrace::_print_fmt::h46deca35c22bc084
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x1046e6b34 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h80b40bec9b25cdb7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x1046ff9ce - core::fmt::write::h367e10cc391177e1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:        0x1046e32e6 - std::io::Write::write_fmt::h69f760cf0ceceb64
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:        0x1046e8949 - std::sys_common::backtrace::_print::h06c56467d8f0565c
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x1046e8949 - std::sys_common::backtrace::print::h83e6ec856bd254a6
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x1046e8949 - std::panicking::default_hook::{{closure}}::h6b461dbc832ae479
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:        0x1046e8430 - std::panicking::default_hook::hf6b37b6d4ff1b717
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:        0x1046e8fb5 - std::panicking::rust_panic_with_hook::hcc0074a2cdf70335
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:        0x1046e8af5 - std::panicking::begin_panic_handler::{{closure}}::hafebb92bbb4f046c
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  12:        0x1046e6f98 - std::sys_common::backtrace::__rust_end_short_backtrace::hbd3b6a5769847c0d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x1046e8a5a - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:        0x1047091eb - std::panicking::begin_panic_fmt::h7722ff9c8a9c34c7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
  15:        0x104260fd3 - eureka::main::h9130df9b52d9e903
  16:        0x10425c83e - core::ops::function::FnOnce::call_once::h9a6658880b37b5fa
  17:        0x10425cc31 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha5f37245e5587bd6
  18:        0x104261364 - std::rt::lang_start::{{closure}}::ha09c09781317f382
  19:        0x1046e9324 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b22ce68aa2879c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  20:        0x1046e9324 - std::panicking::try::do_call::h51a4853c94b1bdea
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  21:        0x1046e9324 - std::panicking::try::ha45bc5eab1f103eb
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  22:        0x1046e9324 - std::panic::catch_unwind::h191bc002afc126a7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  23:        0x1046e9324 - std::rt::lang_start_internal::h0c37a46739a0311d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  24:        0x10426133e - std::rt::lang_start::h4122b0820f04a803
  25:        0x104261286 - _main
```

**Comment by simeg** [comment]
@LironHazan Final try 🙂 I found some code that's being used in rust's cargo code and I don't think it will get any better than that. If it still doesn't work then your configuration is not supported and I can't help any more. You can find the code on the branch.

**Comment by LironHazan** [comment]
@simeg Thanks for your help!
Seems related to my configuration.. anyway, appreciate the help, I'm sure this thread would help others.

**'failed to acquire username/password from local configuration', src/bin/eureka.rs:82:19**

```
>> Idea summary
> jjj
Adding and committing your new idea to test..
Added and committed!
Pushing your new idea..
thread 'main' panicked at 'failed to acquire username/password from local configuration', src/bin/eureka.rs:82:19
stack backtrace:
   0:        0x1080bdd34 - std::backtrace_rs::backtrace::libunwind::trace::h0e344f93e1be12b3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x1080bdd34 - std::backtrace_rs::backtrace::trace_unsynchronized::h547096f273f197d3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1080bdd34 - std::sys_common::backtrace::_print_fmt::h46deca35c22bc084
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x1080bdd34 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h80b40bec9b25cdb7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x1080d6bce - core::fmt::write::h367e10cc391177e1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:        0x1080ba4e6 - std::io::Write::write_fmt::h69f760cf0ceceb64
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:        0x1080bfb49 - std::sys_common::backtrace::_print::h06c56467d8f0565c
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x1080bfb49 - std::sys_common::backtrace::print::h83e6ec856bd254a6
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x1080bfb49 - std::panicking::default_hook::{{closure}}::h6b461dbc832ae479
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:        0x1080bf630 - std::panicking::default_hook::hf6b37b6d4ff1b717
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:        0x1080c01b5 - std::panicking::rust_panic_with_hook::hcc0074a2cdf70335
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:        0x1080bfcf5 - std::panicking::begin_panic_handler::{{closure}}::hafebb92bbb4f046c
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  12:        0x1080be198 - std::sys_common::backtrace::__rust_end_short_backtrace::hbd3b6a5769847c0d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x1080bfc5a - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:        0x1080e03eb - std::panicking::begin_panic_fmt::h7722ff9c8a9c34c7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
  15:        0x107c3a9c3 - eureka::main::h9130df9b52d9e903
  16:        0x107c3622e - core::ops::function::FnOnce::call_once::h9a6658880b37b5fa
  17:        0x107c36621 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha5f37245e5587bd6
  18:        0x107c3ad54 - std::rt::lang_start::{{closure}}::ha09c09781317f382
  19:        0x1080c0524 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b22ce68aa2879c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  20:        0x1080c0524 - std::panicking::try::do_call::h51a4853c94b1bdea
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  21:        0x1080c0524 - std::panicking::try::ha45bc5eab1f103eb
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  22:        0x1080c0524 - std::panic::catch_unwind::h191bc002afc126a7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  23:        0x1080c0524 - std::rt::lang_start_internal::h0c37a46739a0311d
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  24:        0x107c3ad2e - std::rt::lang_start::h4122b0820f04a803
  25:        0x107c3ac76 - _main
```

**Comment by aldy505** [comment]
@simeg Hi. Regarding this, is it possible to just create an option (might be on flags and on config file) to make eureka not push to origin repo? The idea is to let people push it themself to avoid this issue.

**Comment by DanielRivasMD** [comment]
I agree! This is the best solution. This way we could keep using Eureka with the errors.

**Comment by simeg** [comment]
Hi, @aldy505.

Without the pushing functionality eureka can be replaced with a simple bash script 🙂 it could be anyway.

Are you both having the same issues as above? @aldy505 @DanielRivasMD

**Comment by DanielRivasMD** [comment]
I do have exactly the same issue.

That is a good point, however, as it is now (not being able to push) that is the functionality that I can get.

**Comment by skyler-favors** [comment]
Hello,
I was having the same problem listed above,

	'failed to acquire username/password from local configuration',

I am using HTTPS for the remote instead of SSH.

I was finally able to fix it by deleting my old git credentials and replacing them with a fresh PAT.

I followed this tutorial to do that. 
https://www.nih-cfde.org/resource/setting-up-github-authentication/
